name: CD/CD Terraform and Ansible Deployment

on:
  push:
    branches:
      - main
    tags:
      - '*'
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Install Kubespray dependencies
      run: |
        cd kubespray
        pip install -r requirements.txt

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version:  1.5.6

    - name: Terraform Init
      run: |
        cd terraform_files
        terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
    - name: Terraform Apply
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        cd terraform_files
        terraform apply -auto-approve
      env:
        TF_VAR_YC_TOKEN: ${{ secrets.YC_TOKEN }}
        TF_VAR_CLOUD_ID: ${{ secrets.CLOUD_ID }}
        TF_VAR_FOLDER_ID: ${{ secrets.FOLDER_ID }}
        # TF_VAR_META: ${{ secrets.META }}
        TF_VAR_GITHUB_WORKSPACE: ${{ github.workspace }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}